base:
  a: 0.0
  alpha: 0.0
  d: 0.05
  theta: 0.0

base_ext:
  a: 0.0
  alpha: -1.57
  d: 0.0
  theta: 0.0

arm:
  a: 1.0
  alpha: 0.0
  d: 0.0
  theta: 0.0

hand:
  a: 0.5
  alpha: 0.0
  d: 0.0
  theta: 0.0